

CPP = g++
CPPFLAGS = -O2 -Wall -D unix
NVFLAGS = --compiler-options -O2,-fpermissive,-Wall
CPP_COMPILE = -c
CPP_OUT = -o

OBJ_SFX = o
LD_LIB_PFX = -l
LD_LIB_SFX = 

LD = $(CPP)
LDFLAGS = 
LD_OUT = $(CPP_OUT)

include ../platform.mak

