

CPP = cl
CPPFLAGS = /nologo /O2 /MT /EHsc /W3 /D_CONSOLE /DWIN32
NVFLAGS = -Xcompiler /nologo,/O2,/MT,/EHsc,/W3 -D_CONSOLE -DWIN32
CPP_COMPILE = /c
CPP_OUT = /Fo

OBJ_SFX = obj
LD_LIB_PFX = 
LD_LIB_SFX = .lib

LD = link
LDFLAGS = /nologo /subsystem:console /machine:x86 /opt:ref
LD_OUT = /OUT:

include ../platform.mak

